version: '2'
services:
  backend:
    image: sudoaptget/gqlclans:latest
    ports:
      - '8567:8567'
  frontend:
    build: ./frontend
    ports:
      - '8010:8010'
  tests:
    build: ./
    command: tox